[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/api/proxy"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "Range, Accept, Content-Type"
    Access-Control-Expose-Headers = "Content-Range, Content-Length, Accept-Ranges"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
